### ISSUE TITLE
question

### ISSUE THREAD

**Issue by mrc4tt** [Courvix/OVH-DDoS-Alerts#2]
hi.

Usage: node checker [IP Block] [IP Address] [Check Interval]

What are recommended to type of "Check Interval"
And what with IP Block/IP Address?

There are no "example output" on your README! :'(

**You should update README better**
What shall I add here (as example)
![1ZugCPaUCx](https://user-images.githubusercontent.com/5301047/136651456-89a8edd6-9363-4c81-86de-b07767cff511.png)

**Comment by ry-ry-ry** [comment]
The check interval is the number of seconds it will pause before querying the API for the mitigation status again. I personally used 5 seconds when I utilized this repo last.

The path is based on the following API call with the OVH API:
https://api.ovh.com/console/#/ip/{ip}/mitigation/{ipOnMitigation}#GET

So you should grant a GET call to `/ip/{ip}/mitigation/{ipOnMitigation}`, replacing the {ip} and {ipOnMitigation} with the IP address you'd like to query the mitigation status for.

It's been a while since I've used the OVH API, so I cannot recall its exact behavior when mitigation is active however when an IP address is on permanent mitigation, the mitigation mode will be set to 'auto' in the JSON response. However, when the IP address is in forced mitigation mode (under attack), both 'auto' and 'permanent' JSON values are set to 'true'.

This is what the script will check for before deciding an IP address is under attack and sending a Discord alert.

**Comment by mrc4tt** [comment]
Oh, sounds good. ^^

Do you know, what the correct path should be entered?
I getting this: **Error: Invalid path 'ip/{ip}/mitigation/{ipOnMitigation}'** for use that as GET

**Comment by mrc4tt** [comment]
Are this normal, since it wont post on Discord via Webhook?
```
[info] : Checking mitigation status 1:16:44 PM
[crit] : 404 response (The requested object (ipOnMitigation = 51.68.189.255) does not exist)
[info] : Checking mitigation status 1:16:49 PM
IP Address: 51.68.189.255 | Auto Mode: true | Permanent Mode: false
[info] : Checking mitigation status 1:16:54 PM
```

**Comment by ry-ry-ry** [comment]
The 404 is normal if the IP address does not have any mitigation active. If you have permanent mitigation turned off, you'll see the auto mode switch to 'true' when forced mitigation activates.

The code will only send a request to the Discord webhook if both 'permanent' and 'auto' mitigation modes are set to true. In other words, you must enable 'permanent' mitigation for the alerts to work.
